// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uoucrpnoonprqhgxoobb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvdWNycG5vb25wcnFoZ3hvb2JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMDYyMjcsImV4cCI6MjA2MjY4MjIyN30.xNalmqkkxmUmNniQ-MOaWet0nRBK3YQEDOFYoY444yo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);